### ISSUE TITLE
I have go through the CDR documentation and other documents. but Cant get deep details on the above items and how to use them

### ISSUE THREAD

**Issue by gobi-it** [ConsumerDataRight/mock-register#4]
Hi 
Please let me know clarification on following items,
1) x-cds-client-headers
2)  x-fapi-interaction-id 
I have go through the CDR documentation and other documents. but Cant get deep details on the above items and how to use them

![image](https://user-images.githubusercontent.com/59651955/120773812-4e2b3c80-c53f-11eb-8605-98ca3701a456.png)

**Comment by ACCC-DF** [comment]
Hi @gobi-it

The issues raised here should be specific to the CDR Mock Register.

The CDR Mock Register does not contain the Banking APIs or utilise the x-cds-client-headers and x-fapi-interaction-id headers, as these are implemented within a Data Holder solution.

You could raise this question via the [CDR Support Portal](https://cdr-support.zendesk.com/hc/en-us).

Otherwise, for more information, check the [HTTP Headers](https://consumerdatastandardsaustralia.github.io/standards/#http-headers) section of the Consumer Data Standards.
