### ISSUE TITLE
Change TLS certificate in CDR mock-register

### ISSUE THREAD

**Issue by AmilaSamith** [ConsumerDataRight/mock-register#47]
**Describe the bug**
According to the reply to issue #46 we updated TLS certificate in https://github.com/ConsumerDataRight/mock-register/tree/main/Source/CDR.Register.API.Gateway.TLS/Certificates folder and built an image. But still it returns the localhost certificate in TLS handshake.

A issue regarding JWT signature validation occurs in our Dynamic client registration call when calling to endpoint: https://:7006/loopback/MockDataRecipientJwks. Do you have any idea why or any thoughts on how we can resolve it.

**To Reproduce**
1. 
2. 
3. 

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by CDR-AndrewG** [comment]
Hi @AmilaSamith,

Please try the following:



# How To: Replace the certificates used in Mock Register

The TLS and mTLS gateway projects are the external facing endpoints of the Mock Register.  The gateway projects receive the incoming requests and route them to the appropriate backend service.  So when a client connects to the Mock Register, they are connecting via the TLS abd mTLS gateways.

Therefore, to change the certificates that a client interacts with on the TLS/mTLS handshake, the certificate configured for the TLS and mTLS gateways need to be changed.

The steps to do this are outlined below:


1. Clone the Mock Register repository from (GitHub)[https://github.com/ConsumerDataRight/mock-register].

```
git clone https://github.com/ConsumerDataRight/mock-register.git
```

2. Browse to the `mock-register/source/CDR.Register.API.Gateway.TLS/Certificates` folder.

3. Copy the new certificate into this location.

4. Edit the `appsettings.json` file in the `mock-register/source/CDR.Register.API.Gateway.TLS` folder.

5. Change the `Kestrel.Endpoints.Https.Certificate` settings with details for the new certificate:

```
"Kestrel": {
    "Endpoints": {
        "Https": {
            "Url": "https://0.0.0.0:7000",
            "Certificate": {
                "Path": "Certificates/{new certificate file name}",
                "Password": "{new certificate password}"
            }
        }
    }
}
```

For e.g.:

```
"Kestrel": {
    "Endpoints": {
        "Https": {
            "Url": "https://0.0.0.0:7000",
            "Certificate": {
                "Path": "Certificates/new-mock-register-certificate.pfx",
                "Password": "#Password#"
            }
        }
    }
}
```

6. Save the `appSettings.json` file.

7. Edit the `CDR.Register.API.Gateway.TLS.csproj` file in the `mock-register/source/CDR.Register.API.Gateway.TLS` folder, to include the new certificate file into the output.

Add the following elements:

```
<ItemGroup>
    <None Remove="Certificates\{new certificate file name}" />
</ItemGroup>
<ItemGroup>
    <Content Include="Certificates\{new certificate file name}">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
</ItemGroup>
```

For e.g.:

![UpdatedRegisterCertProjectFilej](https://user-images.githubusercontent.com/89497569/158931363-47709cd9-3afb-453a-9e88-7429634b7594.png)

7. Repeat for the mTLS gateway (`mock-register/source/CDR.Register.API.Gateway.mTLS`), if required.

8. From the `mock-register/source` directory, build the container:

```
docker build -t mock-register-updated
```

9. Run the container.

```
docker run -d -h mock-register -p 7000:7000 -p 7001:7001 -p 7006:7006 --name mock-register mock-register-updated
```

10. Browse to an endpoint to check the certificate:

![UpdatedRegisterCert](https://user-images.githubusercontent.com/89497569/158931420-372157b1-be26-4131-95db-76b085113576.png)

**Comment by AmilaSamith** [comment]
Thanks for feedback.

And also if we are using a different host othert han 'localhost', do we want to update HOST attributes in https://github.com/ConsumerDataRight/mock-register/blob/main/Source/CDR.Register.API.Gateway.TLS/gateway-config.json file? Or are there any specific places to configure the new remote host?

**Comment by CDR-AndrewG** [comment]
Hi @AmilaSamith, 

This should help:

# How To: Update the hostname used in Mock Register

In order to change the hostname used in the Mock Register, there are a few places where configuration needs to be updated.

The Mock Register listens for any incoming requests to the designated ports (7000 - 7006) so will respond to any hostname used in the request as long as the traffic is routed to the container port.

For e.g., I add an entry for `cdr.register` to my DNS that points to my Mock Register container.  When I browse to `https://cdr.register:7000/idp/.well-known/openid-configuration` the Open ID Disovery Document is returned successfully.

However, there are fields in the Open ID Disovery Document that are still pointing to the previous hostname.  

![update-register-hostname-1](https://user-images.githubusercontent.com/89497569/159417578-0e0b2ca3-b6fd-4172-89d9-d64402d76d48.png)

In order to change this, the following configuration items need to be updated:

- Edit `CDR.Register.Admin.API\appsettings.Production.json`, and update:

```
"IdentityServerTokenUri": "https://{updated-hostname}:7001/idp/connect/token",
```

For e.g.:
```
"IdentityServerTokenUri": "https://cdr.register:7001/idp/connect/token",
```

- Edit `CDR.Register.Discovery.API\appsettings.Production.json`, and update:

```
"IdentityServerUrl": "https://{updated-hostname}:7000/idp",
"IdentityServerIssuer": "https://{updated-hostname}:7000/idp",
```

For e.g.:
```
"IdentityServerUrl": "https://cdr.register:7000/idp",
"IdentityServerIssuer": "https://cdr.register:7000/idp",
```

- Edit `CDR.Register.IdentityServer\appsettings.Production.json`, and update:

```
"IssuerUri": "https://{updated-hostname}:7000/idp",
"JwksUri": "https://{updated-hostname}:7000/idp/.well-known/openid-configuration/jwks",
"TokenUri": "https://{updated-hostname}:7001/idp/connect/token",
```

For e.g.:
```
"IssuerUri": "https://cdr.register:7000/idp",
"JwksUri": "https://cdr.register:7000/idp/.well-known/openid-configuration/jwks",
"TokenUri": "https://cdr.register:7001/idp/connect/token",
```

- Edit `CDR.Register.SSA.API\appsettings.Production.json`, and update:

```
"IdentityServerUrl": "https://{updated-hostname}:7000/idp",
"IdentityServerIssuer": "https://{updated-hostname}:7000/idp",
```

For e.g.:
```
"IdentityServerUrl": "https://cdr.register:7000/idp",
"IdentityServerIssuer": "https://cdr.register:7000/idp",
```

After the configuration items have been updated, re-build and run the container:

```
docker build -t mock-register-updated .

docker run -d -h mock-register -p 7000:7000 -p 7001:7001 -p 7006:7006 --name mock-register mock-register-updated
```

Once the container is running, browse to an Open ID Discovery Document to check:

![update-register-hostname-2](https://user-images.githubusercontent.com/89497569/159417837-40f3ae40-de0b-42c6-914e-32568ea8cddc.png)

**Comment by CDR-AndrewG** [comment]
Closing this issue as there have been no comments since the help examples were given. Please reach out again if other questions arise in the future.
